/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import regraNegocio.Cliente;
import escritaLeitura.EscritaLeituraCliente;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuk
 */
public class TelaConsultaClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConsultaClientes
     */
    public TelaConsultaClientes() {
        initComponents();
    }
    
    public void consultar(){
        EscritaLeituraCliente elc = new EscritaLeituraCliente();
        Cliente cliente = new Cliente();
        ArrayList<Cliente> leitura = elc.ler();
        
        DefaultTableModel dtm = (DefaultTableModel) jTableConsulta.getModel();
        
        if(jComboBoxTipo.getSelectedItem().toString().equals("Todos")){
            for(Cliente c : leitura){
            dtm.addRow(
                    new Object []{
                        c.getNome(),
                        c.getCpf(),
                        c.getEmail(),
                        c.getLogradouro(),
                        c.getCep()
                    }
            );
        }
        }if(jComboBoxTipo.getSelectedItem().toString().equals("Listar Excluidos")){
            ArrayList<Cliente> excluidos = elc.getDeletados();
            for(Cliente c:excluidos){
                dtm.addRow(
                        new Object []{
                        c.getNome(),
                        c.getCpf(),
                        c.getEmail(),
                        c.getLogradouro(),
                        c.getCep()
                    }
                        
                );
            }
        } else {
            ArrayList<Cliente> resultado = elc.buscar(jComboBoxTipo.getSelectedItem().toString(), jTextFieldArgumento.getText());
            for(Cliente c : resultado){
            dtm.addRow(
                    new Object []{
                        c.getNome(),
                        c.getCpf(),
                        c.getEmail(),
                        c.getLogradouro(),
                        c.getCep()
                    }
            );
        }
        }
    }
    
    
    public void limpar(){
        
        DefaultTableModel dtm =  (DefaultTableModel) jTableConsulta.getModel();
        dtm.getDataVector().removeAllElements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldArgumento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Excluir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consulta de Clientes");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nome", "CPF", "Listar Excluidos" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jLabel1.setText("Consultar por: ");

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "E-mail", "Logradouro", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsulta.getTableHeader().setReorderingAllowed(false);
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);
        if (jTableConsulta.getColumnModel().getColumnCount() > 0) {
            jTableConsulta.getColumnModel().getColumn(0).setResizable(false);
            jTableConsulta.getColumnModel().getColumn(1).setResizable(false);
            jTableConsulta.getColumnModel().getColumn(2).setResizable(false);
            jTableConsulta.getColumnModel().getColumn(3).setResizable(false);
            jTableConsulta.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTextFieldArgumento, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldArgumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EscritaLeituraCliente elc = new EscritaLeituraCliente();
        limpar();
        consultar();
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jTableConsultaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseReleased
        // TODO add your handling code here:
        if(jComboBoxTipo.getSelectedItem().toString().equals("Listar Excluidos") == false){
            int linha = jTableConsulta.rowAtPoint(evt.getPoint());
            if(linha >= 0 && linha < jTableConsulta.getRowCount()){
                jTableConsulta.setRowSelectionInterval(linha, linha);
            
              } else {
                jTableConsulta.clearSelection();
            
             }
            int linhaIndex = jTableConsulta.getSelectedRow();
            if(linhaIndex < 0){
                return ;
            
            }
            if(evt.isPopupTrigger() && evt.getComponent() instanceof JTable){
                jPopupMenu1.show(jTableConsulta, evt.getX(), evt.getY());
            }
        }
        
    }//GEN-LAST:event_jTableConsultaMouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(jComboBoxTipo.getSelectedItem().toString().equals("Listar Excluidos") == false){
            TelaGerenciamentoCliente obj = new TelaGerenciamentoCliente();
        JDesktopPane desk = getDesktopPane();
        desk.add(obj);
        obj.setVisible(true);
        
        int linha = jTableConsulta.getSelectedRow();
        obj.setNome(jTableConsulta.getValueAt(linha, 0).toString());
        obj.setCpf(jTableConsulta.getValueAt(linha, 1).toString());
        obj.setEmail(jTableConsulta.getValueAt(linha, 2).toString());
        obj.setLogradouro(jTableConsulta.getValueAt(linha, 3).toString());
        obj.setCep(jTableConsulta.getValueAt(linha, 4).toString());
        }
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String[] opcoes = {"Sim", "Nao"};
        int excluirCliente = JOptionPane.showOptionDialog(this, "Deseja Realmente Exluir esse Cliente?", "Excluir Cliente", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, frameIcon, opcoes, "Nao");
        if(excluirCliente == 0){
            int linha = jTableConsulta.getSelectedRow();
            String cpf = jTableConsulta.getValueAt(linha, 1).toString();
            EscritaLeituraCliente elc = new EscritaLeituraCliente();
            
            if(elc.deletar(cpf)){
                JOptionPane.showMessageDialog(this,"Cliente Exluido Com Sucesso!");
            }
        }
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldArgumento;
    // End of variables declaration//GEN-END:variables
}
